### ISSUE TITLE
Move NodeJS SDK to schema codegen

### ISSUE THREAD

**Issue by lblackstone** [pulumi/pulumi-kubernetes#1053]
### Problem description

Use the schema to generate the NodeJS SDKs

WIP branch is here: https://github.com/pulumi/pulumi-kubernetes/tree/lblackstone/ts-schema-gen/sdk/nodejs

pulumi/pulumi changes are here: https://github.com/pulumi/pulumi/pull/4325

### TODO:

- [x] Generate SDK from schema
  - [x] Normalize module names
  - [X] Fix infinite loop in type visitors
  - [x] Add custom Pulumi comments to resource classes
- [x] Add overlay for YAML
- [x] Add overlay for Helm
- [x] Add overlay for `apiextensions.CustomResource`
