### ISSUE TITLE
Replace Kubernetes code generation for Python with shared code generator

### ISSUE THREAD

**Issue by leezen** [pulumi/pulumi-kubernetes#1085]
### TODO:

- [x] Generate SDK from schema
	- [x] Fix recursive type causing stack overflow
	- [x] Fix import paths 
	- [x] Fix readme generation
- [x] Add overlay for YAML
- [x] Add overlay for Helm
- [x] Add overlay for `apiextensions.CustomResource`
