### ISSUE TITLE
[Epic] pulumi-kubernetes 4.0 breaking changes

### ISSUE THREAD

**Issue by infin8x** [pulumi/pulumi-kubernetes#1788]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

This epic collects a list of breaking changes we're considering for the next major release of this provider.

- [ ] pulumi/pulumi-kubernetes#1650
- [ ] pulumi/pulumi-kubernetes#1745
- [ ] pulumi/pulumi-kubernetes#1778

**Comment by lblackstone** [comment]
Closing in favor of #2362
