### ISSUE TITLE
[Epic] Implement current "overlay" resources in the provider binary

### ISSUE THREAD

**Issue by AaronFriel** [pulumi/pulumi-kubernetes#1971]
The following resources are implemented as "overlay" resources, hand-written in each of our supported languages. This has increased the cost of supporting these resources and ensuring they handle resource options such as `dependsOn`.

- https://github.com/pulumi/pulumi-kubernetes/issues/1773
- https://github.com/pulumi/pulumi-kubernetes/issues/1923
- https://github.com/pulumi/pulumi-kubernetes/issues/1945
- https://github.com/pulumi/pulumi-kubernetes/issues/1729
- https://github.com/pulumi/pulumi-kubernetes/issues/1642
- https://github.com/pulumi/pulumi-kubernetes/issues/1833
- & more

These resource types are currently only available as overlays:

* `kubernetes:apiextensions.k8s.io:CustomResource`
* `kubernetes:kustomize:Directory`
* `kubernetes:yaml:ConfigFile`
* `kubernetes:yaml:ConfigGroup`

And the Helm Chart resources have an upgrade path via Helm/v3 Release:

* `kubernetes:helm.sh/v2:Chart`
* `kubernetes:helm.sh/v3:Chart`

```[tasklist]
### Tasks
- [ ] https://github.com/pulumi/pulumi-kubernetes/issues/2788
- [ ] https://github.com/pulumi/pulumi/pull/15488
- [ ] https://github.com/pulumi/pulumi/pull/15490
- [ ] https://github.com/pulumi/pulumi-kubernetes/issues/2784
- [ ] https://github.com/pulumi/pulumi-kubernetes/issues/2785
- [ ] https://github.com/pulumi/pulumi-kubernetes/issues/2871
- [ ] https://github.com/pulumi/pulumi/issues/15681
- [ ] https://github.com/pulumi/pulumi-kubernetes/issues/2870
- [ ] https://github.com/pulumi/pulumi-kubernetes/pull/2900
- [ ] https://github.com/pulumi/pulumi-kubernetes/issues/2868
- [ ] https://github.com/pulumi/pulumi-kubernetes/issues/2847
- [ ] https://github.com/pulumi/pulumi-kubernetes/issues/2787
- [ ] https://github.com/pulumi/pulumi-kubernetes/issues/2786
- [ ] https://github.com/pulumi/pulumi/issues/6933
- [ ] https://github.com/pulumi/pulumi-kubernetes/issues/2181
- [ ] https://github.com/pulumi/pulumi-kubernetes/issues/2910
- [ ] https://github.com/pulumi/pulumi-kubernetes/pull/2918
- [ ] Update the "pulumi new" template
- [ ] Add new examples
- [ ] Add an integration test
- [ ] Support for unconfigured provider
```
```[tasklist]
### Resolves
- [ ] https://github.com/pulumi/pulumi-kubernetes/issues/1833
- [ ] https://github.com/pulumi/pulumi-kubernetes/issues/1773
- [ ] https://github.com/pulumi/pulumi-kubernetes/issues/1174
- [ ] https://github.com/pulumi/pulumi-kubernetes/issues/1173
- [ ] https://github.com/pulumi/pulumi-kubernetes/issues/907
- [ ] https://github.com/pulumi/pulumi-kubernetes/issues/1108
- [ ] https://github.com/pulumi/pulumi-kubernetes/issues/1960
- [ ] https://github.com/pulumi/pulumi-kubernetes/issues/1689
- [ ] https://github.com/pulumi/pulumi-kubernetes/issues/1208
- [ ] https://github.com/pulumi/pulumi-kubernetes/issues/2134
- [ ] https://github.com/pulumi/pulumi-kubernetes/issues/1072
```

**Comment by EronWright** [comment]
Some questions to resolve:
1. are there blocking upstream issues (e.g. codegen, transform support in MLCs)?
2. how would this be delivered (e.g. new provider vs. new resources in k provider).
3. which overlay resources are specifically being developed? (e.g. `Chart`, `Release`, `Directory`, `ConfigGroup`, `ConfigFile`)

**Comment by geowalrus4gh** [comment]
Its really confusing. Document says CustomResource is supported by YAML runtime and even gave me an example.
![image](https://github.com/pulumi/pulumi-kubernetes/assets/33422391/97681c86-6005-42f1-aaab-28e306900867)

**Comment by EronWright** [comment]
@geowalrus4gh sorry, the documentation is incorrect, but the good news is that support is coming within a few weeks. Please subscribe to this issue: https://github.com/pulumi/pulumi-kubernetes/issues/2787

**Comment by lblackstone** [comment]
🎉
