### ISSUE TITLE
[Epic] Kubernetes 4.0

### ISSUE THREAD

**Issue by kpitzen** [pulumi/pulumi-kubernetes#2362]
# Overview

Since the 3.0 release in April 2021, over 160 resources have been added including patch functionality, flow control, and helm releases. With over 236,000 Pulumi managed resources, the Kubernetes provider continues to be one of the most popular providers, second only to AWS. 

For this iteration of the Kubernetes provider, we are improving the user experience with a focus on consistency, efficiency, and Kubernetes best practices. This set of improvements includes:
- [Server-Side Apply by default](https://github.com/pulumi/pulumi-kubernetes/issues/1556)
- [Consistent output properties between SDKs](https://github.com/pulumi/pulumi-kubernetes/issues/1650)
- [Removing support for deprecated Helm.v2 SDK](https://github.com/pulumi/pulumi-kubernetes/issues/1789)
- ~[Begin overlay implementation](https://github.com/pulumi/pulumi-kubernetes/issues/1971)~
- [Change minimum supported k8s version to v1.13](https://github.com/pulumi/pulumi-kubernetes/issues/2386)

# References

- [FAQ](https://docs.google.com/document/d/1uOQIqK19bv-3_ZlPoGwN7wDzjE9tz3lcSueprKNhFAg/edit)

# Milestones

- [x] [Server-Side Apply by default](https://github.com/pulumi/pulumi-kubernetes/issues/1556)
- [x] [Automatically fall back to CSA for previews if SSA fails](https://github.com/pulumi/pulumi-kubernetes/issues/2411)
- [x] [Consistent output properties between SDKs](https://github.com/pulumi/pulumi-kubernetes/issues/1650)
- [x] [Removing support for deprecated Helm.v2 SDK](https://github.com/pulumi/pulumi-kubernetes/issues/1789)
- [x] ~[Respect provider config settings and prevent fallback](https://github.com/pulumi/pulumi-kubernetes/issues/2357)~ (Replaced by https://github.com/pulumi/pulumi-kubernetes/issues/2423, which is not a breaking change) -- Feature shipped in v3.28.1 since it's not a breaking change
- [x] [Change minimum supported k8s version to v1.13](https://github.com/pulumi/pulumi-kubernetes/issues/2386)
- [x] [Remove deprecated enableDryRun flag](https://github.com/pulumi/pulumi-kubernetes/issues/2399)
- [x] [Remove deprecated enableReplaceCRD flag](https://github.com/pulumi/pulumi-kubernetes/issues/2401)
- [x] [Fix diff logic to correct for out of band drift/changes](https://github.com/pulumi/pulumi-kubernetes/issues/2404)
- [x] [Drop support for legacy pulumi.com/initialApiVersion annotation](https://github.com/pulumi/pulumi-kubernetes/issues/2442)
- [x] [Drop usage of last-applied-configuration annotation](https://github.com/pulumi/pulumi-kubernetes/issues/2444)
- [x] ~[Stop storing statuses and server generated metadata in state](https://github.com/pulumi/pulumi-kubernetes/issues/2335)~
- [x] [Poor performance when SSA is enabled](https://github.com/pulumi/pulumi-kubernetes/issues/2427)
- [x] [Create migration guide](https://github.com/pulumi/pulumi-kubernetes/issues/2440)

## Release tasks
- [ ] Blog post
- [ ] Docs updates
- [ ] Examples/templates updates

---

We decided to pull this change out of the v4 scope since it's additive / non-breaking.
- [ ] [Begin overlay implementation](https://github.com/pulumi/pulumi-kubernetes/issues/1971)
  - [ ] kubernetes:apiextenstions.k8s.io:CustomResource
  - [ ] kubernetes:kustomize:Directory
  - [x] ~kubernetes:helm:v2:Chart~
  - [ ] kubernetes:helm:v3:Chart
  - [ ] kubernetes:yaml:ConfigFile
  - [ ] kubernetes:yaml:ConfigGroup

# Notes
- https://github.com/pulumi/pulumi/issues/7346 May now be unnecessary (though we should reconcile items here against that list)

**Comment by lblackstone** [comment]
The first release candidate is now published for testing https://github.com/pulumi/pulumi-kubernetes/tree/v4.0.0-rc.1

**Comment by mnlumi** [comment]
The release is being cut now: https://github.com/pulumi/pulumi-kubernetes/actions/runs/5601213165

**Comment by mnlumi** [comment]
4.0 has been released. https://github.com/pulumi/pulumi-kubernetes/releases/tag/v4.0.0
