### ISSUE TITLE
[Epic] Kubernetes Testing improvements

### ISSUE THREAD

**Issue by mjeffryes** [pulumi/pulumi-kubernetes#2774]
Iterating on the Kubernetes code base has been slow in part due to the challenge of verifying and testing changes. There has been limited options for unittesting, and e2e tests are very slow (~1hour to run the suite). We believe a few targeted investments can improve the situation materially.

Effort: 4 eng weeks
Goal/Impact: Grow unit test coverage from %19 -> 30%, Reduce time for running a single e2e test by 10min and the whole suite by (X) min

``` tasklist
- [ ] Unittests for provider lifecycle
- [ ] Unittests for resource lifecycle: Check
- [ ] Unittests for resource lifecycle: Diff
- [ ] Unittests for resource lifecycle:  Read
- [ ] Unittests for resource lifecycle:  Create
- [ ] Unittests for resource lifecycle:  Update
- [ ] Unittests for resource lifecycle:  Delete
- [ ] Uniittests for invokes: Invoke
- [ ] Uniittests for invokes: StreamInvoke
- [ ] https://github.com/pulumi/pulumi-kubernetes/issues/2243
```
