### ISSUE TITLE
Develop Component resource for: kubernetes:kustomize:Directory

### ISSUE THREAD

**Issue by mjeffryes** [pulumi/pulumi-kubernetes#2786]
```[tasklist]
### Resolves
- [ ] https://github.com/pulumi/pulumi-kubernetes/issues/1966
- [ ] https://github.com/pulumi/pulumi-kubernetes/issues/1884
```

```[tasklist]
### Tasks
- [ ] docs for Kustomize MLC
- [x] Kustomize MLC
```
